# action.yml
name: "Complete a test run in the Qase TMS"
description: "Complete a test run in the Qase TMS."
inputs:
  token:
    description: "Token for Qase API"
    required: true
  project:
    description: "Project code in Qase"
    required: true
  id:
    description: "ID of the test run to complete"
    required: true
  verbose:
    description: "Verbose output"
    required: false
    default: "false"
outputs:
  id:
    description: "ID of the created test run"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.token }}
    - ${{ inputs.project }}
    - ${{ inputs.id }}
    - ${{ inputs.verbose }}
