# action.yml
name: "Create a milestone in the Qase TMS"
description: "Create a milestone in the Qase TMS."
inputs:
  token:
    description: "Token for Qase API"
    required: true
  project:
    description: "Project code in Qase"
    required: true
  title:
    description: "Title of the milestone"
    required: true
  description:
    description: "Description of the milestone"
    required: true
  status:
    description: "Status of the milestone. Allowed values: active, completed"
    required: false
  due_date:
    description: "Due date of the milestone. Format: YYYY-MM-DD"
    required: false
  verbose:
    description: "Enable verbose output"
    required: false
    default: "false"
outputs:
  id:
    description: "ID of the created milestone"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.token }}
    - ${{ inputs.project }}
    - ${{ inputs.title }}
    - ${{ inputs.description }}
    - ${{ inputs.status }}
    - ${{ inputs.due_date }}
    - ${{ inputs.verbose }}
