# action.yml
name: "Create an environment in the Qase TMS"
description: "Create an environment in the Qase TMS."
inputs:
  token:
    description: "Token for Qase API"
    required: true
  project:
    description: "Project code in Qase"
    required: true
  title:
    description: "Title of the environment"
    required: true
  slug:
    description: "Slug of the environment"
    required: true
  description:
    description: "Description of the environment"
    required: false
  host:
    description: "Host of the environment"
    required: false
  verbose:
    description: "Enable verbose output"
    required: false
    default: "false"
outputs:
  slug:
    description: "slug of the created environment"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.token }}
    - ${{ inputs.project }}
    - ${{ inputs.title }}
    - ${{ inputs.slug }}
    - ${{ inputs.description }}
    - ${{ inputs.host }}
    - ${{ inputs.verbose }}
